version: "3.3"
services:
    voice-recognition:
        build:
            context: ./
            dockerfile: Dockerfile
        networks:
            - app-network
        restart: unless-stopped
networks:
    app-network:
